import type { Player } from './types';

// Roster published with the app: a device with no saved data starts with these
// players. To update: Roster tab → Export, then replace this array with the
// downloaded file's contents and redeploy.
export const DEFAULT_PLAYERS: Player[] = [
  {
    id: 'mrnag4a65q7lbc',
    name: 'אופק',
    rating: 4,
    playstyle: 'defensive',
    chemistry: ['mrnagchcdzzhr8', 'mrnbaphxaunwx5'],
    avoid: [],
  },
  {
    id: 'mrnagchcdzzhr8',
    name: 'ירין',
    rating: 5,
    playstyle: 'attacking',
    chemistry: ['mrnag4a65q7lbc'],
    avoid: [],
  },
  {
    id: 'mrnbaphxaunwx5',
    name: 'יועד',
    rating: 3.5,
    playstyle: 'defensive',
    chemistry: ['mrnag4a65q7lbc', 'mrnbpty5a4wm8a'],
    avoid: [],
  },
  {
    id: 'mrnbl5r1l3ajni',
    name: 'חנש',
    rating: 4,
    playstyle: 'gk',
    chemistry: [],
    avoid: [],
  },
  {
    id: 'mrnblunakh31sv',
    name: 'חנגל',
    rating: 5,
    playstyle: 'attacking',
    chemistry: [],
    avoid: [],
  },
  {
    id: 'mrnbmufovnd0sv',
    name: 'הלחמי',
    rating: 4.5,
    playstyle: 'attacking',
    chemistry: [],
    avoid: [],
  },
  {
    id: 'mrnbn3l9028544',
    name: 'עובדיה',
    rating: 3,
    playstyle: 'mixed',
    chemistry: [],
    avoid: [],
  },
  {
    id: 'mrnbnlhn7akle6',
    name: 'ניב',
    rating: 4.5,
    playstyle: 'mixed',
    chemistry: ['mrnboh9tj4rwut'],
    avoid: [],
  },
  {
    id: 'mrnboh9tj4rwut',
    name: 'יוני',
    rating: 4,
    playstyle: 'attacking',
    chemistry: ['mrnbnlhn7akle6'],
    avoid: [],
  },
  {
    id: 'mrnbostx04orwl',
    name: 'דור',
    rating: 2.5,
    playstyle: 'defensive',
    chemistry: [],
    avoid: [],
  },
  {
    id: 'mrnbpty5a4wm8a',
    name: 'טאקו',
    rating: 4.5,
    playstyle: 'defensive',
    chemistry: ['mrnbaphxaunwx5'],
    avoid: [],
  },
  {
    id: 'mrnbqhf6r8my4o',
    name: 'עומרי',
    rating: 3,
    playstyle: 'attacking',
    chemistry: [],
    avoid: [],
  },
  {
    id: 'mrnbqtnuo5cgvy',
    name: 'ניר',
    rating: 3.5,
    playstyle: 'mixed',
    chemistry: [],
    avoid: [],
  },
  {
    id: 'mrnbrnjux6uflu',
    name: 'שגב',
    rating: 5,
    playstyle: 'mixed',
    chemistry: [],
    avoid: [],
  },
  {
    id: 'mrnbrzo03kcs1t',
    name: 'טום',
    rating: 5,
    playstyle: 'mixed',
    chemistry: [],
    avoid: [],
  },
  {
    id: 'mrnbtchahbjur2',
    name: 'עילאי פינק.',
    rating: 5,
    playstyle: 'attacking',
    chemistry: [],
    avoid: [],
  },
];
